import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import TanStackProvider from "@/provider/tanstackProvider";
import TopHeader from "@/components/shared/TopHeader";
import NavBar from "@/components/shared/NavBar";
import Hero from "@/components/shared/Hero";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Destiny Abroad",
  description: "Generated by Destiny Abroad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanStackProvider>
          <TopHeader />
          <NavBar />

          {children}
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
